"""clean architecture

Revision ID: 6e43f105de6a
Revises: 
Create Date: 2026-06-06 16:03:26.760652

"""
from __future__ import annotations

from typing import Sequence, Union



revision: str = '6e43f105de6a'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
