from __future__ import annotations

from typing import Any, Protocol, runtime_checkable

from app.hr_analytics.domain.entities import GenerationResult, QueryResult
from app.workspace.domain.entities import Project


@runtime_checkable
class ILLMClient(Protocol):
    async def generate(self, prompt: str, model: str | None = None) -> GenerationResult: ...
    async def list_models(self) -> list[dict[str, str]]: ...
    async def health(self) -> dict[str, Any]: ...


@runtime_checkable
class IQueryExecutor(Protocol):
    def run(self, sql: str) -> QueryResult: ...


@runtime_checkable
class IPromptAssembler(Protocol):
    def assemble(self, project: Project, question: str) -> str: ...


@runtime_checkable
class IMetadataService(Protocol):
    """Full interface for the metadata service used across the HR analytics pipeline."""

    def get_main_view(self) -> dict[str, Any]: ...
    def get_sql_template(self, template_id: str) -> dict[str, Any] | None: ...
    def get_status_sql(self, status: str) -> str | None: ...
    def health_check(self) -> Any: ...
    def normalize_question(self, question: str) -> str: ...
    def find_semantic_matches(
        self, question: str, max_matches: int = 10
    ) -> list[dict[str, Any]]: ...
    def list_intents(self) -> list[dict[str, Any]]: ...
    def list_sql_templates(self) -> list[dict[str, Any]]: ...
    def build_metadata_context_for_intent(self, intent_id: str) -> dict[str, Any]: ...
    def build_schema_context_for_prompt(self) -> str: ...
    def get_visualization_for_intent(self, intent_id: str) -> dict[str, Any] | None: ...
    def get_visualization_for_report(self, report_id: str) -> dict[str, Any] | None: ...
    def get_sensitive_columns(self) -> list[str]: ...


@runtime_checkable
class ISQLValidator(Protocol):
    def validate(self, sql: str, question: str | None = None) -> dict[str, Any]: ...


@runtime_checkable
class IChatRepository(Protocol):
    """Persistence interface for chat sessions — keeps routes free of ORM."""

    async def list_sessions(self) -> list[Any]: ...
    async def get_session(self, session_id: str) -> Any | None: ...
    async def create_session(self, title: str, project_id: str | None, model_name: str) -> Any: ...
    async def update_session(self, session_id: str, **fields: Any) -> Any | None: ...
    async def delete_session(self, session_id: str) -> bool: ...
    async def add_message(
        self,
        session_id: str,
        role: str,
        content: str,
        sql: str | None,
        error: str | None,
        query_result: dict | None,
    ) -> Any | None: ...
