from __future__ import annotations

import asyncio
import re
from collections.abc import Mapping
from dataclasses import asdict, dataclass, field, is_dataclass
from pathlib import Path
from typing import Any

from app.core.constants import MIN_GROUP_SIZE_FLOOR
from app.core.sensitive_columns import SENSITIVE_COLUMNS_FLOOR, resolve_sensitive_columns
from app.hr_analytics.use_cases.sql.ast_guard import analyze_sql
from app.infrastructure.metadata.service import get_metadata_service

"""
sql_validator.py
----------------
Strict SQL guardrail validator for HR BI Assistant Phase 2.


Responsibility:
    - Validate every SQL statement before query_executor.py runs it.
    - Enforce the Controlled SQL-based MVP contract:
        * SELECT/WITH-only
        * exactly one statement
        * only hr_mvp.vw_hr_employee_analytics v
        * no raw HR tables
        * no JOINs
        * no SELECT *
        * no sensitive/personal columns
        * no visible employee-level output
        * v.is_active = TRUE filter for analytic SQL
    - Allow only safe status SQL outputs such as:
        SELECT 'DATA_GAP' AS status;
        SELECT 'ACCESS_DENIED' AS status;

The implementation intentionally uses a conservative regex/scanner approach so it
can run without external dependencies in the MVP. For production, adding an AST
parser such as sqlglot is recommended, but the same policy checks should remain.
"""


JsonDict = dict[str, Any]


class SQLValidationError(RuntimeError):
    """Base exception for SQL validation failures."""


@dataclass
class SQLValidatorConfig:
    """Runtime configuration for SQLValidator."""

    main_view: str = "hr_mvp.vw_hr_employee_analytics"
    required_alias: str = "v"
    schema_name: str = "hr_mvp"
    allow_with_clause: bool = True
    allow_status_only_sql: bool = True
    require_active_filter: bool = True
    max_limit: int = 500
    minimum_group_size: int = MIN_GROUP_SIZE_FLOOR
    reject_sql_comments: bool = True
    source_name: str = "sql_validator"
    # Additive AST parse-tree guard (defense in depth) on top of the regex checks.
    enable_ast_guard: bool = True


@dataclass
class SQLValidationIssue:
    """One validation issue returned to the orchestrator/logs."""

    rule_id: str
    severity: str
    status: str
    message: str
    evidence: str | None = None
    suggestion: str | None = None

    def to_dict(self) -> JsonDict:
        return asdict(self)


@dataclass
class SQLValidationResult:
    """Standard output shape consumed by llm_orchestrator.py."""

    status: str
    route: str
    source: str
    is_valid: bool
    can_execute_sql: bool
    sql: str | None = None
    normalized_sql: str | None = None
    validation_status: str | None = None
    is_status_only: bool = False
    status_value: str | None = None
    statement_type: str | None = None
    detected_relations: list[JsonDict] = field(default_factory=list)
    cte_names: list[str] = field(default_factory=list)
    referenced_columns: list[str] = field(default_factory=list)
    selected_expressions: list[str] = field(default_factory=list)
    selected_columns: list[str] = field(default_factory=list)
    violations: list[JsonDict] = field(default_factory=list)
    warnings: list[str] = field(default_factory=list)
    policy_hints: list[str] = field(default_factory=list)
    errors: list[str] = field(default_factory=list)
    metadata: JsonDict = field(default_factory=dict)

    @property
    def is_executable(self) -> bool:
        return self.can_execute_sql

    def to_dict(self) -> JsonDict:
        payload = asdict(self)
        payload["is_executable"] = self.is_executable
        if self.validation_status is None:
            payload["validation_status"] = self.status
        return payload


class SQLValidator:
    """
    Validate SQL generated by sql_template_engine.py or SQL generator.

    Public methods supported by the orchestrator:
        validate(sql=..., context=...)
        run(sql=..., context=...)
        arun(sql=..., context=...)
        __call__(sql=..., context=...)
    """

    STATUS_ROUTE_BY_VALUE = {
        "DATA_GAP": "GAP",
        "ACCESS_DENIED": "REJECT",
        "OUT_OF_SCOPE": "REJECT",
        "NEEDS_CLARIFICATION": "NEEDS_CLARIFICATION",
        "SQL_VALIDATION_FAILED": "REJECT",
    }

    BLOCKED_STATEMENTS = {
        "INSERT",
        "UPDATE",
        "DELETE",
        "DROP",
        "ALTER",
        "CREATE",
        "TRUNCATE",
        "MERGE",
        "GRANT",
        "REVOKE",
        "COPY",
        "CALL",
        "EXECUTE",
        "DO",
        "VACUUM",
        "ANALYZE",
        "REFRESH",
        "COMMENT",
        "SET",
        "RESET",
    }

    RAW_TABLES = {
        "hr_mvp.hr_employees",
        "hr_mvp.hr_contracts",
        "hr_mvp.hr_employee_education",
        "hr_mvp.hr_education_levels",
        "hr_mvp.hr_departments",
        "hr_mvp.hr_positions",
        "hr_mvp.hr_locations",
        "hr_mvp.hr_age_groups",
        "hr_mvp.hr_workforce_targets",
        "hr_mvp.hr_calendar",
    }

    INTERNAL_SCHEMAS_BLOCKLIST = {
        "information_schema",
        "pg_catalog",
    }

    # Canonical, non-weakenable floor (see app.core.sensitive_columns). Metadata
    # may widen this set via _load_sensitive_columns; it can never shrink it.
    DEFAULT_SENSITIVE_COLUMNS = SENSITIVE_COLUMNS_FLOOR

    RAW_DATE_COLUMNS = {
        "birth_date",
        "hire_date",
        "contract_start_date",
        "contract_end_date",
    }

    DATA_GAP_QUESTION_PATTERNS = {
        "city_level_analysis": ["شهر", "شهری", "هر شهر"],
        "contractor_productivity_analysis": [
            "بهره وری",
            "بهره‌وری",
            "عملکرد پیمانکار",
            "کارایی پیمانکار",
        ],
        "monthly_hiring_analysis": ["جذب ماهانه", "ماهانه جذب", "در هر ماه"],
        "business_growth_alignment": ["افزایش کار", "حجم کار", "رشد کار", "هماهنگ بوده"],
        "education_training_need_analysis": ["نیاز آموزشی", "دوره تخصصی", "آموزش"],
    }

    def __init__(
        self,
        metadata_service: Any | None = None,
        *,
        metadata_dir: str | Path | None = None,
        strict: bool = True,
    ) -> None:
        if metadata_service is not None:
            self.metadata = metadata_service
        elif get_metadata_service is not None:
            self.metadata = get_metadata_service(metadata_dir=metadata_dir, strict=False)
        else:
            self.metadata = None

        self.config = self._build_config(self.metadata, strict=strict)
        self.allowed_columns = self._load_allowed_columns(self.metadata)
        self.sensitive_columns = self._load_sensitive_columns(self.metadata)
        self.status_sql_values = self._load_status_sql_values(self.metadata)

    # ------------------------------------------------------------------
    # Public API
    # ------------------------------------------------------------------

    def validate(
        self,
        sql: str | Mapping[str, Any] | None = None,
        *,
        context: Any | None = None,
        question: str | None = None,
        metadata: Any | None = None,
        sql_plan: Mapping[str, Any] | None = None,
        intent_result: Mapping[str, Any] | None = None,
        route_result: Mapping[str, Any] | None = None,
        **_: Any,
    ) -> JsonDict:
        """Validate SQL and return a serializable result dictionary."""

        service = metadata or self.metadata
        sql_text = self._resolve_sql(sql, context=context, sql_plan=sql_plan)
        question_text = self._resolve_question(question, context=context)

        if not sql_text:
            return self._finalize(
                sql=None,
                normalized_sql=None,
                issues=[
                    SQLValidationIssue(
                        rule_id="SQL_EMPTY",
                        severity="error",
                        status="SQL_VALIDATION_FAILED",
                        message="No SQL statement was provided to the validator.",
                    )
                ],
                warnings=[],
                policy_hints=[],
                route_hint=self._route_hint(route_result=route_result, intent_result=intent_result),
            ).to_dict()

        normalized_sql = self._normalize_sql(sql_text)
        issues: list[SQLValidationIssue] = []
        warnings: list[str] = []
        policy_hints: list[str] = []

        # 1) Status-only SQL is allowed but must not be executed as an analytic query.
        status_value = self._detect_status_only_sql(normalized_sql)
        if status_value:
            route = self.STATUS_ROUTE_BY_VALUE.get(status_value, "REJECT")
            return SQLValidationResult(
                status=status_value,
                validation_status=status_value,
                route=route,
                source=self.config.source_name,
                is_valid=True,
                can_execute_sql=False,
                sql=sql_text,
                normalized_sql=normalized_sql,
                is_status_only=True,
                status_value=status_value,
                statement_type="SELECT",
                policy_hints=[
                    "Status-only SQL should go directly to the response layer and should not be executed as an analytic query."
                ],
                metadata={"status_only_sql": True},
            ).to_dict()

        # 2) Fast checks that do not require structure extraction.
        issues.extend(self._validate_basic_safety(normalized_sql))
        issues.extend(self._validate_statement_type(normalized_sql))
        issues.extend(self._validate_blocked_patterns(normalized_sql))

        # 2b) Independent AST parse-tree guard (defense in depth).
        if self.config.enable_ast_guard:
            issues.extend(self._validate_ast_structure(normalized_sql))

        cte_names = self._extract_cte_names(normalized_sql)
        detected_relations = self._extract_relations(normalized_sql)
        referenced_columns = sorted(set(self._extract_qualified_columns(normalized_sql)))
        selected_expressions = self._extract_selected_expressions(normalized_sql)
        selected_columns = sorted(set(self._extract_direct_selected_columns(selected_expressions)))

        # 3) Relation, alias and column checks.
        issues.extend(self._validate_relations(detected_relations, cte_names))
        issues.extend(self._validate_columns(referenced_columns))
        issues.extend(self._validate_sensitive_columns(normalized_sql, selected_columns))
        issues.extend(
            self._validate_visible_restricted_columns(
                selected_columns, selected_expressions, normalized_sql
            )
        )

        # 4) Business / semantic rules.
        # If is_active filter is missing, attempt to inject it before failing.
        active_issues = self._validate_active_filter(normalized_sql)
        if active_issues:
            repaired = self._inject_active_filter(normalized_sql)
            if repaired is not None:
                normalized_sql = repaired
                sql_text = repaired
                active_issues = []
        issues.extend(active_issues)
        issues.extend(self._validate_semantic_rules(normalized_sql, question_text))
        issues.extend(self._validate_data_gap_rules(normalized_sql, question_text))
        issues.extend(self._validate_limit(normalized_sql))

        # 5) Helpful non-blocking policy hints.
        if self._contains_group_by(normalized_sql):
            policy_hints.append(
                f"Post-execution suppression must enforce minimum_group_size >= {self.config.minimum_group_size}."
            )
        if service is None:
            warnings.append("Metadata service was not available; validator used built-in defaults.")

        result = self._finalize(
            sql=sql_text,
            normalized_sql=normalized_sql,
            issues=issues,
            warnings=warnings,
            policy_hints=policy_hints,
            route_hint=self._route_hint(route_result=route_result, intent_result=intent_result),
            detected_relations=detected_relations,
            cte_names=cte_names,
            referenced_columns=referenced_columns,
            selected_expressions=selected_expressions,
            selected_columns=selected_columns,
            statement_type=self._statement_type(normalized_sql),
        )
        return result.to_dict()

    def run(self, *args: Any, **kwargs: Any) -> JsonDict:
        return self.validate(*args, **kwargs)

    async def arun(self, *args: Any, **kwargs: Any) -> JsonDict:
        await asyncio.sleep(0)
        return self.validate(*args, **kwargs)

    def __call__(self, *args: Any, **kwargs: Any) -> JsonDict:
        return self.validate(*args, **kwargs)

    # ------------------------------------------------------------------
    # Validation stages
    # ------------------------------------------------------------------

    def _validate_basic_safety(self, sql: str) -> list[SQLValidationIssue]:
        issues: list[SQLValidationIssue] = []

        statements = self._split_sql_statements(sql)
        if len(statements) != 1:
            issues.append(
                SQLValidationIssue(
                    rule_id="SQL_SINGLE_STATEMENT_ONLY",
                    severity="error",
                    status="SQL_VALIDATION_FAILED",
                    message="SQL must contain exactly one statement.",
                    evidence=f"statement_count={len(statements)}",
                )
            )

        if self.config.reject_sql_comments and ("--" in sql or "/*" in sql or "*/" in sql):
            issues.append(
                SQLValidationIssue(
                    rule_id="SQL_COMMENTS_NOT_ALLOWED",
                    severity="error",
                    status="SQL_VALIDATION_FAILED",
                    message="SQL comments are not allowed in generated SQL.",
                )
            )

        if "`" in sql:
            issues.append(
                SQLValidationIssue(
                    rule_id="SQL_BACKTICKS_NOT_ALLOWED",
                    severity="error",
                    status="SQL_VALIDATION_FAILED",
                    message="Backtick quoting is not allowed. Use normal PostgreSQL identifiers from metadata only.",
                )
            )

        if "{" in sql or "}" in sql:
            issues.append(
                SQLValidationIssue(
                    rule_id="SQL_UNRESOLVED_PLACEHOLDER",
                    severity="error",
                    status="SQL_VALIDATION_FAILED",
                    message="SQL contains unresolved template placeholders. Parameters must be injected before validation/execution.",
                    evidence=self._find_first(r"\{[^}]+\}", sql),
                )
            )

        return issues

    def _validate_statement_type(self, sql: str) -> list[SQLValidationIssue]:
        statement_type = self._statement_type(sql)
        if statement_type == "SELECT":
            return []
        if statement_type == "WITH" and self.config.allow_with_clause:
            if self._has_top_level_final_select(sql):
                return []
            return [
                SQLValidationIssue(
                    rule_id="SQL_WITH_FINAL_SELECT_REQUIRED",
                    severity="error",
                    status="SQL_VALIDATION_FAILED",
                    message="WITH queries are allowed only when the final top-level statement is SELECT.",
                )
            ]
        return [
            SQLValidationIssue(
                rule_id="SQL_SELECT_ONLY",
                severity="error",
                status="SQL_VALIDATION_FAILED",
                message="Only SELECT queries, or WITH queries whose final statement is SELECT, are allowed.",
                evidence=statement_type,
            )
        ]

    def _validate_blocked_patterns(self, sql: str) -> list[SQLValidationIssue]:
        issues: list[SQLValidationIssue] = []
        upper_sql = self._strip_string_literals(sql).upper()

        for keyword in sorted(self.BLOCKED_STATEMENTS):
            if re.search(rf"\b{re.escape(keyword)}\b", upper_sql):
                issues.append(
                    SQLValidationIssue(
                        rule_id="SQL_DML_DDL_BLOCKED",
                        severity="error",
                        status="SQL_VALIDATION_FAILED",
                        message="DML/DDL/admin SQL commands are not allowed.",
                        evidence=keyword,
                    )
                )

        if re.search(r"\bSELECT\s+\*", upper_sql) or re.search(r"\bV\s*\.\s*\*", upper_sql):
            issues.append(
                SQLValidationIssue(
                    rule_id="SQL_SELECT_STAR_BLOCKED",
                    severity="error",
                    status="SQL_VALIDATION_FAILED",
                    message="SELECT * or v.* is not allowed.",
                )
            )

        if re.search(r"\b[A-Z_]*JOIN\b", upper_sql):
            issues.append(
                SQLValidationIssue(
                    rule_id="SQL_JOIN_BLOCKED",
                    severity="error",
                    status="SQL_VALIDATION_FAILED",
                    message="JOIN is not allowed in Phase 2 SQL. The analytics View already resolves joins.",
                )
            )

        unsafe_literals = [" OR 1=1", " AND 1=1", " OR TRUE", "UNION SELECT"]
        for pattern in unsafe_literals:
            if pattern in upper_sql:
                issues.append(
                    SQLValidationIssue(
                        rule_id="SQL_INJECTION_PATTERN_BLOCKED",
                        severity="error",
                        status="SQL_VALIDATION_FAILED",
                        message="Potential SQL injection pattern detected.",
                        evidence=pattern.strip(),
                    )
                )

        for raw_table in sorted(self.RAW_TABLES):
            if re.search(rf"(?<![\w.]){re.escape(raw_table)}(?![\w.])", sql, flags=re.IGNORECASE):
                issues.append(
                    SQLValidationIssue(
                        rule_id="SQL_RAW_TABLE_BLOCKED",
                        severity="error",
                        status="SQL_VALIDATION_FAILED",
                        message="Raw HR tables are not allowed. Use only the controlled analytics View.",
                        evidence=raw_table,
                    )
                )

        for blocked_schema in self.INTERNAL_SCHEMAS_BLOCKLIST:
            if re.search(rf"\b{re.escape(blocked_schema)}\b", sql, flags=re.IGNORECASE):
                issues.append(
                    SQLValidationIssue(
                        rule_id="SQL_INTERNAL_SCHEMA_BLOCKED",
                        severity="error",
                        status="SQL_VALIDATION_FAILED",
                        message="Internal database catalogs/schemas are not allowed.",
                        evidence=blocked_schema,
                    )
                )

        if re.search(r"\bpg_[A-Za-z0-9_]+\b", sql, flags=re.IGNORECASE):
            issues.append(
                SQLValidationIssue(
                    rule_id="SQL_PG_INTERNAL_OBJECT_BLOCKED",
                    severity="error",
                    status="SQL_VALIDATION_FAILED",
                    message="PostgreSQL internal objects are not allowed.",
                )
            )

        return issues

    def _validate_relations(
        self, relations: list[JsonDict], cte_names: list[str]
    ) -> list[SQLValidationIssue]:
        issues: list[SQLValidationIssue] = []
        cte_name_set = {name.lower() for name in cte_names}
        allowed_view = self.config.main_view.lower()
        allowed_view_basename = allowed_view.split(".")[-1]

        if not relations:
            issues.append(
                SQLValidationIssue(
                    rule_id="SQL_FROM_REQUIRED",
                    severity="error",
                    status="SQL_VALIDATION_FAILED",
                    message="Analytic SQL must have a FROM clause that uses the controlled View.",
                )
            )
            return issues

        view_seen = False
        for relation in relations:
            name = str(relation.get("name", "")).lower()
            alias = str(relation.get("alias") or "").lower()

            if name in cte_name_set:
                continue

            if name == allowed_view_basename:
                issues.append(
                    SQLValidationIssue(
                        rule_id="SQL_SCHEMA_PREFIX_REQUIRED",
                        severity="error",
                        status="SQL_VALIDATION_FAILED",
                        message="The analytics View must be referenced with schema prefix hr_mvp.",
                        evidence=relation.get("name"),
                    )
                )
                continue

            if name != allowed_view:
                issues.append(
                    SQLValidationIssue(
                        rule_id="SQL_RELATION_NOT_ALLOWED",
                        severity="error",
                        status="SQL_VALIDATION_FAILED",
                        message="SQL may only read from hr_mvp.vw_hr_employee_analytics v or internal CTEs derived from it.",
                        evidence=relation.get("name"),
                    )
                )
                continue

            view_seen = True
            if alias != self.config.required_alias.lower():
                issues.append(
                    SQLValidationIssue(
                        rule_id="SQL_REQUIRED_ALIAS_MISSING",
                        severity="error",
                        status="SQL_VALIDATION_FAILED",
                        message="The analytics View must use the standard alias v.",
                        evidence=f"alias={relation.get('alias')}",
                    )
                )

        if not view_seen:
            issues.append(
                SQLValidationIssue(
                    rule_id="SQL_MAIN_VIEW_NOT_FOUND",
                    severity="error",
                    status="SQL_VALIDATION_FAILED",
                    message="SQL must ultimately read from hr_mvp.vw_hr_employee_analytics v.",
                )
            )
        return issues

    def _validate_columns(self, referenced_columns: list[str]) -> list[SQLValidationIssue]:
        issues: list[SQLValidationIssue] = []
        for column in referenced_columns:
            if column not in self.allowed_columns:
                issues.append(
                    SQLValidationIssue(
                        rule_id="SQL_COLUMN_NOT_IN_VIEW_METADATA",
                        severity="error",
                        status="SQL_VALIDATION_FAILED",
                        message="SQL references a column that is not defined in the allowed View metadata.",
                        evidence=f"v.{column}",
                    )
                )
        return issues

    def _validate_sensitive_columns(
        self, sql: str, selected_columns: list[str]
    ) -> list[SQLValidationIssue]:
        issues: list[SQLValidationIssue] = []
        masked = self._strip_string_literals(sql)
        for column in sorted(self.sensitive_columns):
            if re.search(rf"\b{re.escape(column)}\b", masked, flags=re.IGNORECASE):
                issues.append(
                    SQLValidationIssue(
                        rule_id="SQL_SENSITIVE_COLUMN_BLOCKED",
                        severity="error",
                        status="ACCESS_DENIED",
                        message="SQL references a sensitive or personal column that must never be exposed.",
                        evidence=column,
                    )
                )

        for column in selected_columns:
            if column in self.sensitive_columns:
                issues.append(
                    SQLValidationIssue(
                        rule_id="SQL_SENSITIVE_COLUMN_SELECTED",
                        severity="error",
                        status="ACCESS_DENIED",
                        message="SQL selects a sensitive or personal column.",
                        evidence=column,
                    )
                )
        return issues

    def _validate_visible_restricted_columns(
        self,
        selected_columns: list[str],
        selected_expressions: list[str],
        sql: str,
    ) -> list[SQLValidationIssue]:
        issues: list[SQLValidationIssue] = []

        # employee_id is allowed only inside COUNT/COUNT DISTINCT.
        normalized_no_count_employee_id = re.sub(
            r"COUNT\s*\(\s*(?:DISTINCT\s+)?(?:v\s*\.\s*)?employee_id\s*\)",
            "COUNT_EMPLOYEE_ID_ALLOWED",
            sql,
            flags=re.IGNORECASE,
        )
        if "employee_id" in selected_columns or re.search(
            r"\bSELECT\s+(?:v\s*\.\s*)?employee_id\b",
            normalized_no_count_employee_id,
            flags=re.IGNORECASE,
        ):
            issues.append(
                SQLValidationIssue(
                    rule_id="SQL_EMPLOYEE_ID_COUNT_ONLY",
                    severity="error",
                    status="ACCESS_DENIED",
                    message="employee_id may only be used inside COUNT/COUNT DISTINCT and must not be visible in output.",
                    evidence="employee_id",
                )
            )

        for column in sorted(self.RAW_DATE_COLUMNS):
            if column in selected_columns:
                issues.append(
                    SQLValidationIssue(
                        rule_id="SQL_RAW_DATE_VISIBLE_OUTPUT_BLOCKED",
                        severity="error",
                        status="ACCESS_DENIED",
                        message="Raw individual-level dates must not be selected as visible output. Use derived fields such as age, hire_year, or service_years.",
                        evidence=column,
                    )
                )

        # Low-risk technical identifiers are not fatal if used only with a business label,
        # because current templates include department_id for grouping. We warn instead.
        for column in ("department_id", "location_id", "position_id"):
            if column in selected_columns:
                issues.append(
                    SQLValidationIssue(
                        rule_id="SQL_TECHNICAL_ID_VISIBLE_OUTPUT_WARN",
                        severity="warning",
                        status="VALID_WITH_WARNINGS",
                        message="Technical identifiers should be hidden or used only for internal grouping in the final response.",
                        evidence=column,
                        suggestion="Response builder can drop this column before display if a human-readable label exists.",
                    )
                )
        return issues

    _ACTIVE_FILTER_PATTERN = re.compile(
        r"\bv\s*\.\s*is_active\s*=\s*(TRUE|'true'|1)\b", flags=re.IGNORECASE
    )
    _WHERE_CLAUSE_TERMINATORS = ("GROUP BY", "ORDER BY", "HAVING", "LIMIT", "WINDOW")

    @classmethod
    def _has_active_filter_in_where(cls, sql: str) -> bool:
        """True only when v.is_active = TRUE appears as a real filter in WHERE.

        A textual match anywhere in the statement is not enough: a projected
        expression such as `(v.is_active = TRUE) AS flag` in the SELECT list
        would satisfy a naive check while the query actually runs with no
        active-employee filter. We scope the match to the WHERE clause body so
        the guard enforces what it claims.
        """
        where_match = re.search(r"\bWHERE\b", sql, flags=re.IGNORECASE)
        if not where_match:
            return False
        where_region = sql[where_match.end() :]
        end = len(where_region)
        for keyword in cls._WHERE_CLAUSE_TERMINATORS:
            terminator = re.search(rf"\b{keyword}\b", where_region, flags=re.IGNORECASE)
            if terminator:
                end = min(end, terminator.start())
        return cls._ACTIVE_FILTER_PATTERN.search(where_region[:end]) is not None

    def _validate_active_filter(self, sql: str) -> list[SQLValidationIssue]:
        if not self.config.require_active_filter:
            return []
        if self._has_active_filter_in_where(sql):
            return []
        return [
            SQLValidationIssue(
                rule_id="SQL_ACTIVE_FILTER_REQUIRED",
                severity="error",
                status="SQL_VALIDATION_FAILED",
                message="All analytic SQL must include the default filter v.is_active = TRUE.",
                evidence="v.is_active = TRUE",
            )
        ]

    @staticmethod
    def _inject_active_filter(sql: str) -> str | None:
        """Inject v.is_active = TRUE into SQL that is missing it.

        Returns the patched SQL, or None if the structure is too complex to patch safely
        (e.g. CTEs with multiple SELECT blocks where injection point is ambiguous).
        """
        # Do not touch CTEs — too risky to inject in the right place.
        if re.search(r"\bWITH\b", sql, flags=re.IGNORECASE):
            return None

        active_clause = "v.is_active = TRUE"

        # SQL already has a WHERE clause — append with AND.
        where_match = re.search(r"\bWHERE\b", sql, flags=re.IGNORECASE)
        if where_match:
            insert_pos = where_match.end()
            return sql[:insert_pos] + f" {active_clause} AND" + sql[insert_pos:]

        # No WHERE clause — insert before GROUP BY / ORDER BY / LIMIT / HAVING, or at end.
        for keyword in ("GROUP BY", "ORDER BY", "HAVING", "LIMIT"):
            kw_match = re.search(rf"\b{keyword}\b", sql, flags=re.IGNORECASE)
            if kw_match:
                insert_pos = kw_match.start()
                return sql[:insert_pos] + f"WHERE {active_clause}\n" + sql[insert_pos:]

        # Append before trailing semicolon or at end.
        sql_stripped = sql.rstrip()
        if sql_stripped.endswith(";"):
            return sql_stripped[:-1] + f"\nWHERE {active_clause};"
        return sql_stripped + f"\nWHERE {active_clause}"

    def _validate_semantic_rules(self, sql: str, question: str | None) -> list[SQLValidationIssue]:
        issues: list[SQLValidationIssue] = []
        masked = self._strip_string_literals(sql)

        if re.search(
            r"SUM\s*\(\s*v\s*\.\s*department_approved_headcount\s*\)", masked, flags=re.IGNORECASE
        ):
            issues.append(
                SQLValidationIssue(
                    rule_id="SQL_APPROVED_HEADCOUNT_SUM_BLOCKED",
                    severity="error",
                    status="SQL_VALIDATION_FAILED",
                    message="Do not SUM(v.department_approved_headcount) over employee rows because it duplicates approved headcount.",
                    suggestion="Use MAX(v.department_approved_headcount) at department level, then aggregate department-level results if needed.",
                )
            )

        if question and self._text_contains_any(
            question,
            [
                "بیشترین جذب",
                "کمترین جذب",
                "سال بیشترین",
                "سال کمترین",
                "most hiring",
                "least hiring",
            ],
        ):
            if re.search(
                r"\b(MAX|MIN)\s*\(\s*v\s*\.\s*hire_year\s*\)", masked, flags=re.IGNORECASE
            ):
                issues.append(
                    SQLValidationIssue(
                        rule_id="SQL_HIRING_YEAR_TOP_BOTTOM_AGGREGATION_WRONG",
                        severity="error",
                        status="SQL_VALIDATION_FAILED",
                        message="For year with most/least hires, aggregate by hire_year and order by employee_count; do not use MIN/MAX(hire_year).",
                        suggestion="GROUP BY v.hire_year ORDER BY COUNT(v.employee_id) DESC/ASC LIMIT 1.",
                    )
                )

        if self._looks_like_percentage_query(masked):
            if "NULLIF" not in masked.upper():
                issues.append(
                    SQLValidationIssue(
                        rule_id="SQL_PERCENTAGE_REQUIRES_NULLIF",
                        severity="error",
                        status="SQL_VALIDATION_FAILED",
                        message="Percentage calculations must use NULLIF in the denominator to avoid division-by-zero errors.",
                    )
                )

        if re.search(
            r"\bc\s*\.\s*is_current\b|\bee\s*\.\s*is_latest\b", masked, flags=re.IGNORECASE
        ):
            issues.append(
                SQLValidationIssue(
                    rule_id="SQL_RAW_TABLE_ALIAS_LOGIC_BLOCKED",
                    severity="error",
                    status="SQL_VALIDATION_FAILED",
                    message="current contract and latest education are already resolved inside the View. Do not use c.is_current or ee.is_latest.",
                )
            )

        return issues

    def _validate_data_gap_rules(self, sql: str, question: str | None) -> list[SQLValidationIssue]:
        issues: list[SQLValidationIssue] = []
        question_norm = self._normalize_persian_text(question or "")

        # "شهریور" (the Shamsi month) contains "شهر" (city) as a plain
        # substring — strip it out before the city-term check so month-filter
        # questions aren't misclassified as city-level data gaps.
        question_norm_no_month = question_norm.replace("شهریور", "")
        if re.search(r"\bv\s*\.\s*city\b", sql, flags=re.IGNORECASE) or self._text_contains_any(
            question_norm_no_month, self.DATA_GAP_QUESTION_PATTERNS["city_level_analysis"]
        ):
            issues.append(
                SQLValidationIssue(
                    rule_id="SQL_CITY_LEVEL_DATA_GAP",
                    severity="error",
                    status="DATA_GAP",
                    message="City-level data is not reliable in the current MVP and must return DATA_GAP.",
                    evidence="city",
                )
            )

        for rule_id, terms in self.DATA_GAP_QUESTION_PATTERNS.items():
            if rule_id == "city_level_analysis":
                continue
            if self._text_contains_any(question_norm, terms):
                issues.append(
                    SQLValidationIssue(
                        rule_id=f"SQL_{rule_id.upper()}_DATA_GAP",
                        severity="error",
                        status="DATA_GAP",
                        message="The question is HR-related, but required data/business rules are not available in the current MVP.",
                        evidence=rule_id,
                        suggestion="Return SELECT 'DATA_GAP' AS status; and register the missing data/rule in Gap Manager.",
                    )
                )

        return issues

    def _validate_limit(self, sql: str) -> list[SQLValidationIssue]:
        issues: list[SQLValidationIssue] = []
        match = re.search(r"\bLIMIT\s+(\d+)\b", sql, flags=re.IGNORECASE)
        if match:
            limit_value = int(match.group(1))
            if limit_value > self.config.max_limit:
                issues.append(
                    SQLValidationIssue(
                        rule_id="SQL_LIMIT_TOO_HIGH",
                        severity="error",
                        status="SQL_VALIDATION_FAILED",
                        message=f"LIMIT must not exceed {self.config.max_limit} rows.",
                        evidence=str(limit_value),
                    )
                )
        return issues

    # ------------------------------------------------------------------
    # Finalization
    # ------------------------------------------------------------------

    def _finalize(
        self,
        *,
        sql: str | None,
        normalized_sql: str | None,
        issues: list[SQLValidationIssue],
        warnings: list[str],
        policy_hints: list[str],
        route_hint: str | None = None,
        detected_relations: list[JsonDict] | None = None,
        cte_names: list[str] | None = None,
        referenced_columns: list[str] | None = None,
        selected_expressions: list[str] | None = None,
        selected_columns: list[str] | None = None,
        statement_type: str | None = None,
    ) -> SQLValidationResult:
        fatal_issues = [issue for issue in issues if issue.severity == "error"]
        warning_issues = [issue for issue in issues if issue.severity != "error"]
        warnings = [*warnings, *[issue.message for issue in warning_issues]]

        if fatal_issues:
            status = self._status_from_issues(fatal_issues)
            route = self.STATUS_ROUTE_BY_VALUE.get(status, route_hint or "REJECT")
            return SQLValidationResult(
                status=status,
                validation_status=status,
                route=route,
                source=self.config.source_name,
                is_valid=False,
                can_execute_sql=False,
                sql=sql,
                normalized_sql=normalized_sql,
                statement_type=statement_type,
                detected_relations=detected_relations or [],
                cte_names=cte_names or [],
                referenced_columns=referenced_columns or [],
                selected_expressions=selected_expressions or [],
                selected_columns=selected_columns or [],
                violations=[issue.to_dict() for issue in fatal_issues],
                warnings=list(dict.fromkeys(warnings)),
                policy_hints=list(dict.fromkeys(policy_hints)),
                errors=[issue.message for issue in fatal_issues],
                metadata={
                    "fatal_issue_count": len(fatal_issues),
                    "warning_issue_count": len(warning_issues),
                },
            )

        return SQLValidationResult(
            status="VALID",
            validation_status="VALID",
            route=route_hint or "SQL",
            source=self.config.source_name,
            is_valid=True,
            can_execute_sql=True,
            sql=sql,
            normalized_sql=normalized_sql,
            statement_type=statement_type,
            detected_relations=detected_relations or [],
            cte_names=cte_names or [],
            referenced_columns=referenced_columns or [],
            selected_expressions=selected_expressions or [],
            selected_columns=selected_columns or [],
            violations=[],
            warnings=list(dict.fromkeys(warnings)),
            policy_hints=list(dict.fromkeys(policy_hints)),
            errors=[],
            metadata={"fatal_issue_count": 0, "warning_issue_count": len(warning_issues)},
        )

    @staticmethod
    def _status_from_issues(issues: list[SQLValidationIssue]) -> str:
        # Privacy/security denial is the highest priority, then known data gaps,
        # then generic SQL validation failures.
        priorities = [
            "ACCESS_DENIED",
            "DATA_GAP",
            "OUT_OF_SCOPE",
            "NEEDS_CLARIFICATION",
            "SQL_VALIDATION_FAILED",
        ]
        statuses = {issue.status for issue in issues}
        for status in priorities:
            if status in statuses:
                return status
        return "SQL_VALIDATION_FAILED"

    # ------------------------------------------------------------------
    # SQL scanning helpers
    # ------------------------------------------------------------------

    @staticmethod
    def _normalize_sql(sql: str) -> str:
        text = str(sql).strip()
        # Remove common code fences if a model accidentally included them.
        text = re.sub(r"^```(?:sql)?\s*", "", text, flags=re.IGNORECASE)
        text = re.sub(r"\s*```$", "", text)
        # Normalize smart quotes that may come from copy/paste.
        text = text.replace("‘", "'").replace("’", "'").replace("“", '"').replace("”", '"')
        # Trim trailing whitespace but keep SQL formatting for readable logs.
        lines = [line.rstrip() for line in text.splitlines()]
        return "\n".join(lines).strip()

    @staticmethod
    def _normalize_for_compare(sql: str) -> str:
        return re.sub(r"\s+", " ", sql.strip().rstrip(";")).upper()

    def _detect_status_only_sql(self, sql: str) -> str | None:
        if not self.config.allow_status_only_sql:
            return None
        match = re.fullmatch(
            r"\s*SELECT\s+'(DATA_GAP|ACCESS_DENIED|OUT_OF_SCOPE|NEEDS_CLARIFICATION|SQL_VALIDATION_FAILED)'\s+AS\s+status\s*;?\s*",
            sql,
            flags=re.IGNORECASE,
        )
        if match:
            return match.group(1).upper()
        normalized = self._normalize_for_compare(sql)
        for status_sql in self.status_sql_values:
            if normalized == self._normalize_for_compare(status_sql):
                status = self._detect_status_only_sql(status_sql)
                if status:
                    return status
        return None

    def _split_sql_statements(self, sql: str) -> list[str]:
        statements: list[str] = []
        start = 0
        in_single_quote = False
        i = 0
        while i < len(sql):
            ch = sql[i]
            if ch == "'":
                if in_single_quote and i + 1 < len(sql) and sql[i + 1] == "'":
                    i += 2
                    continue
                in_single_quote = not in_single_quote
            elif ch == ";" and not in_single_quote:
                part = sql[start:i].strip()
                if part:
                    statements.append(part)
                start = i + 1
            i += 1
        tail = sql[start:].strip()
        if tail:
            statements.append(tail)
        return statements

    @staticmethod
    def _strip_string_literals(sql: str) -> str:
        result: list[str] = []
        in_single_quote = False
        i = 0
        while i < len(sql):
            ch = sql[i]
            if ch == "'":
                result.append(" ")
                if in_single_quote and i + 1 < len(sql) and sql[i + 1] == "'":
                    result.append(" ")
                    i += 2
                    continue
                in_single_quote = not in_single_quote
                i += 1
                continue
            result.append(" " if in_single_quote else ch)
            i += 1
        return "".join(result)

    @staticmethod
    def _statement_type(sql: str) -> str:
        match = re.match(r"\s*([A-Za-z]+)", sql)
        return match.group(1).upper() if match else "UNKNOWN"

    def _has_top_level_final_select(self, sql: str) -> bool:
        positions = self._find_top_level_keyword_positions(sql, "SELECT")
        return bool(positions)

    @staticmethod
    def _find_top_level_keyword_positions(sql: str, keyword: str) -> list[int]:
        positions: list[int] = []
        upper = sql.upper()
        keyword_upper = keyword.upper()
        in_single_quote = False
        depth = 0
        i = 0
        while i < len(sql):
            ch = sql[i]
            if ch == "'":
                if in_single_quote and i + 1 < len(sql) and sql[i + 1] == "'":
                    i += 2
                    continue
                in_single_quote = not in_single_quote
                i += 1
                continue
            if not in_single_quote:
                if ch == "(":
                    depth += 1
                elif ch == ")" and depth > 0:
                    depth -= 1
                elif depth == 0 and upper.startswith(keyword_upper, i):
                    before = upper[i - 1] if i > 0 else " "
                    after = (
                        upper[i + len(keyword_upper)] if i + len(keyword_upper) < len(sql) else " "
                    )
                    if not (before.isalnum() or before == "_") and not (
                        after.isalnum() or after == "_"
                    ):
                        positions.append(i)
                        i += len(keyword_upper)
                        continue
            i += 1
        return positions

    def _extract_cte_names(self, sql: str) -> list[str]:
        if self._statement_type(sql) != "WITH":
            return []
        names: list[str] = []
        # Conservative extraction. It captures names in patterns like:
        # WITH department_level AS (...), other AS (...)
        for match in re.finditer(
            r"(?:\bWITH\b|,)\s*([A-Za-z_][A-Za-z0-9_]*)\s+AS\s*\(", sql, flags=re.IGNORECASE
        ):
            names.append(match.group(1))
        return list(dict.fromkeys(names))

    def _extract_relations(self, sql: str) -> list[JsonDict]:
        masked = self._strip_string_literals(sql)
        relations: list[JsonDict] = []
        for match in re.finditer(
            r"\bFROM\s+([A-Za-z_][A-Za-z0-9_]*(?:\.[A-Za-z_][A-Za-z0-9_]*)?)\s*(?:AS\s+)?([A-Za-z_][A-Za-z0-9_]*)?",
            masked,
            flags=re.IGNORECASE,
        ):
            relation_name = match.group(1)
            alias = match.group(2)
            # Avoid treating SQL clauses as aliases when no alias exists.
            if alias and alias.upper() in {
                "WHERE",
                "GROUP",
                "ORDER",
                "HAVING",
                "LIMIT",
                "UNION",
                "WINDOW",
            }:
                alias = None
            relations.append(
                {"name": relation_name, "alias": alias, "start": match.start(), "end": match.end()}
            )
        return relations

    def _extract_qualified_columns(self, sql: str) -> list[str]:
        masked = self._strip_string_literals(sql)
        alias = re.escape(self.config.required_alias)
        return [
            m.group(1)
            for m in re.finditer(
                rf"\b{alias}\s*\.\s*([A-Za-z_][A-Za-z0-9_]*)\b", masked, flags=re.IGNORECASE
            )
        ]

    def _extract_selected_expressions(self, sql: str) -> list[str]:
        select_positions = self._find_top_level_keyword_positions(sql, "SELECT")
        if not select_positions:
            return []
        select_pos = select_positions[-1]
        from_pos = self._find_next_top_level_keyword_position(
            sql, "FROM", start=select_pos + len("SELECT")
        )
        if from_pos is None:
            return []
        select_list = sql[select_pos + len("SELECT") : from_pos].strip()
        return self._split_top_level_commas(select_list)

    def _find_next_top_level_keyword_position(
        self, sql: str, keyword: str, *, start: int = 0
    ) -> int | None:
        positions = self._find_top_level_keyword_positions(sql[start:], keyword)
        if not positions:
            return None
        return start + positions[0]

    @staticmethod
    def _split_top_level_commas(text: str) -> list[str]:
        parts: list[str] = []
        start = 0
        depth = 0
        in_single_quote = False
        i = 0
        while i < len(text):
            ch = text[i]
            if ch == "'":
                if in_single_quote and i + 1 < len(text) and text[i + 1] == "'":
                    i += 2
                    continue
                in_single_quote = not in_single_quote
            elif not in_single_quote:
                if ch == "(":
                    depth += 1
                elif ch == ")" and depth > 0:
                    depth -= 1
                elif ch == "," and depth == 0:
                    part = text[start:i].strip()
                    if part:
                        parts.append(part)
                    start = i + 1
            i += 1
        tail = text[start:].strip()
        if tail:
            parts.append(tail)
        return parts

    def _extract_direct_selected_columns(self, selected_expressions: list[str]) -> list[str]:
        selected: list[str] = []
        for expression in selected_expressions:
            cleaned = re.sub(
                r"\s+AS\s+[A-Za-z_][A-Za-z0-9_]*\s*$", "", expression, flags=re.IGNORECASE
            ).strip()
            cleaned = re.sub(r"\s+[A-Za-z_][A-Za-z0-9_]*\s*$", "", cleaned).strip()
            match = re.fullmatch(
                r"(?:v\s*\.\s*)?([A-Za-z_][A-Za-z0-9_]*)", cleaned, flags=re.IGNORECASE
            )
            if match:
                selected.append(match.group(1))
        return selected

    # ------------------------------------------------------------------
    # Metadata/config helpers
    # ------------------------------------------------------------------

    def _build_config(self, service: Any | None, *, strict: bool) -> SQLValidatorConfig:
        config = SQLValidatorConfig()
        if service is not None:
            try:
                view = service.get_main_view()
                config.main_view = str(view.get("name") or config.main_view)
                config.required_alias = str(view.get("alias") or config.required_alias)
            except Exception:
                pass
            try:
                rules = service.get_document("sql_validator_rules")
                allowed_sql = (
                    rules.get("allowed_sql", {})
                    if isinstance(rules.get("allowed_sql"), dict)
                    else {}
                )
                config.max_limit = int(
                    (allowed_sql.get("allowed_limit") or {}).get("max_limit", config.max_limit)
                )
                contract = (
                    rules.get("validator_contract", {})
                    if isinstance(rules.get("validator_contract"), dict)
                    else {}
                )
                config.allow_status_only_sql = bool(
                    contract.get("allow_status_only_sql_without_view", config.allow_status_only_sql)
                )
            except Exception:
                pass
            try:
                # Metadata may only raise the privacy threshold above the floor.
                config.minimum_group_size = max(
                    MIN_GROUP_SIZE_FLOOR,
                    int(service.get_min_group_size(default=config.minimum_group_size)),
                )
            except Exception:
                pass
        config.require_active_filter = strict
        return config

    def _load_allowed_columns(self, service: Any | None) -> set[str]:
        if service is None:
            return {
                "employee_id",
                "is_active",
                "gender",
                "marital_status",
                "birth_date",
                "age",
                "age_group_title",
                "hire_date",
                "hire_year",
                "service_years",
                "department_id",
                "department_code",
                "department_name",
                "service_domain",
                "parent_department_id",
                "department_level",
                "department_approved_headcount",
                "criticality_level",
                "location_id",
                "province",
                "city",
                "site_name",
                "location_type",
                "position_id",
                "position_code",
                "position_title",
                "position_level",
                "job_family",
                "is_expert_role",
                "min_education_rank",
                "education_title",
                "education_rank",
                "education_category",
                "field_of_study",
                "graduation_year",
                "employment_type",
                "contract_type",
                "is_contractor",
                "contract_start_date",
                "contract_end_date",
            }
        try:
            return {
                str(col.get("name"))
                for col in service.get_columns(include_restricted=True)
                if col.get("name")
            }
        except Exception:
            return self._load_allowed_columns(None)

    def _validate_ast_structure(self, sql: str) -> list[SQLValidationIssue]:
        """Parse-tree defense-in-depth guard layered on top of the regex checks.

        Mirrors the structural invariants (single SELECT, allowed view only, no
        stacked statements / set ops / SELECT *) on the sqlglot AST so that
        subquery/CTE-based evasions the regex layer can miss are still caught.
        """
        result = analyze_sql(
            sql, allowed_view=self.config.main_view, allowed_schema=self.config.schema_name
        )
        if result.ok:
            return []
        return [
            SQLValidationIssue(
                rule_id=violation.rule_id,
                severity="error",
                status="SQL_VALIDATION_FAILED",
                message=violation.message,
            )
            for violation in result.violations
        ]

    def _load_sensitive_columns(self, service: Any | None) -> set[str]:
        # Single source: floor plus metadata additions, with fail-safe logging.
        return resolve_sensitive_columns(service)

    def _load_status_sql_values(self, service: Any | None) -> list[str]:
        values = [
            "SELECT 'DATA_GAP' AS status;",
            "SELECT 'ACCESS_DENIED' AS status;",
            "SELECT 'OUT_OF_SCOPE' AS status;",
            "SELECT 'NEEDS_CLARIFICATION' AS status;",
            "SELECT 'SQL_VALIDATION_FAILED' AS status;",
        ]
        if service is not None:
            for status in [
                "DATA_GAP",
                "ACCESS_DENIED",
                "OUT_OF_SCOPE",
                "NEEDS_CLARIFICATION",
                "SQL_VALIDATION_FAILED",
            ]:
                try:
                    status_sql = service.get_status_sql(status)
                    if status_sql:
                        values.append(status_sql)
                except Exception:
                    pass
        return list(dict.fromkeys(values))

    # ------------------------------------------------------------------
    # Small utilities
    # ------------------------------------------------------------------

    def _resolve_sql(
        self,
        sql: str | Mapping[str, Any] | None,
        *,
        context: Any | None,
        sql_plan: Mapping[str, Any] | None,
    ) -> str | None:
        if isinstance(sql, str):
            return sql
        if isinstance(sql, Mapping):
            return str(sql.get("sql") or sql.get("generated_sql") or "") or None
        if sql_plan is not None:
            return str(sql_plan.get("sql") or sql_plan.get("generated_sql") or "") or None
        for attr in ("sql_plan", "generated_sql", "sql", "query"):
            value = self._get_context_value(context, attr)
            if isinstance(value, Mapping):
                nested = value.get("sql") or value.get("generated_sql")
                if nested:
                    return str(nested)
            if isinstance(value, str) and value.strip():
                return value
        return None

    def _resolve_question(self, question: str | None, *, context: Any | None) -> str | None:
        if question:
            return question
        for attr in ("question", "user_question", "normalized_question"):
            value = self._get_context_value(context, attr)
            if isinstance(value, str) and value.strip():
                return value
        return None

    @staticmethod
    def _get_context_value(context: Any | None, key: str) -> Any:
        if context is None:
            return None
        if isinstance(context, Mapping):
            return context.get(key)
        if is_dataclass(context):
            return getattr(context, key, None)
        return getattr(context, key, None)

    @staticmethod
    def _route_hint(
        *, route_result: Mapping[str, Any] | None, intent_result: Mapping[str, Any] | None
    ) -> str | None:
        for payload in (route_result, intent_result):
            if not payload:
                continue
            route = payload.get("route") or payload.get("detected_route")
            if route:
                return str(route)
        return None

    @staticmethod
    def _normalize_persian_text(text: str) -> str:
        replacements = {
            "ي": "ی",
            "ك": "ک",
            "ة": "ه",
            "ۀ": "ه",
            "ؤ": "و",
            "إ": "ا",
            "أ": "ا",
        }
        for src, dst in replacements.items():
            text = text.replace(src, dst)
        text = re.sub(r"\s+", " ", text.strip())
        return text

    def _text_contains_any(self, text: str, terms: list[str]) -> bool:
        normalized_text = self._normalize_persian_text(text)
        return any(self._normalize_persian_text(term) in normalized_text for term in terms)

    @staticmethod
    def _find_first(pattern: str, text: str) -> str | None:
        match = re.search(pattern, text)
        return match.group(0) if match else None

    @staticmethod
    def _contains_group_by(sql: str) -> bool:
        return bool(re.search(r"\bGROUP\s+BY\b", sql, flags=re.IGNORECASE))

    @staticmethod
    def _looks_like_percentage_query(sql_without_literals: str) -> bool:
        upper = sql_without_literals.upper()
        return (
            "PERCENTAGE" in upper
            or " درصد" in upper
            or ("ROUND" in upper and "/" in upper and "COUNT" in upper)
        )


# ---------------------------------------------------------------------------
# Module-level singleton helpers
# ---------------------------------------------------------------------------

_validator: SQLValidator | None = None


def get_sql_validator(
    *,
    reload: bool = False,
    metadata_service: Any | None = None,
    metadata_dir: str | Path | None = None,
    strict: bool = True,
) -> SQLValidator:
    """Return a process-wide SQLValidator singleton."""
    global _validator
    if reload or _validator is None or metadata_service is not None or metadata_dir is not None:
        _validator = SQLValidator(
            metadata_service=metadata_service, metadata_dir=metadata_dir, strict=strict
        )
    return _validator
