from __future__ import annotations

"""
llm_sql_fallback.py
-------------------
Controlled LLM SQL fallback coordinator.

It is used only when:
- route is SQL
- question is valid/safe
- required columns exist in the analytics View
- no exact metadata SQL template can satisfy the requested shape

The generated SQL must still pass sql_validator.py before execution.
"""

from dataclasses import asdict, dataclass, field
from typing import Any

try:
    from .llm_client import LLMClient
    from .prompt_builder import PromptBuilder
except Exception:  # pragma: no cover
    from llm_client import LLMClient  # type: ignore
    from prompt_builder import PromptBuilder  # type: ignore

JsonDict = dict[str, Any]


@dataclass
class LLMSQLFallbackResult:
    status: str
    route: str = "SQL"
    source: str = "llm_sql_fallback"
    sql: str | None = None
    can_execute_sql: bool = False
    generation_mode: str = "llm_fallback"
    reason: str | None = None
    prompt: str | None = None
    modular_context: JsonDict = field(default_factory=dict)
    warnings: list[str] = field(default_factory=list)
    errors: list[str] = field(default_factory=list)
    metadata: JsonDict = field(default_factory=dict)

    def to_dict(self) -> JsonDict:
        return asdict(self)


class LLMSQLFallback:
    def __init__(self, *, metadata_service: Any | None = None, llm_client: LLMClient | None = None, prompt_builder: PromptBuilder | None = None) -> None:
        self.metadata = metadata_service
        self.llm_client = llm_client or LLMClient()
        self.prompt_builder = prompt_builder or PromptBuilder(metadata_service=metadata_service)

    def generate(self, *, question: str | None = None, context: Any | None = None, metadata: Any | None = None, schema_context: str | None = None, **_: Any) -> JsonDict:
        service = metadata or self.metadata
        q = question or getattr(context, "normalized_question", None) or getattr(context, "question", "")
        built = self.prompt_builder.build_sql_fallback_prompt(question=str(q), context=context, metadata=service, schema_context=schema_context)
        if not self.llm_client.is_configured:
            return LLMSQLFallbackResult(
                status="NEEDS_LLM_SQL_FALLBACK",
                can_execute_sql=False,
                reason="LLM fallback is required but no LLM provider is configured.",
                prompt=built.prompt,
                modular_context=built.modular_context,
                warnings=["Configure LLM_PROVIDER=ollama or LLM_PROVIDER=openai_compatible to enable this fallback."],
                metadata={"schema_context_supplied": bool(schema_context)},
            ).to_dict()
        llm_result = self.llm_client.generate_sql(built.prompt)
        if llm_result.sql:
            return LLMSQLFallbackResult(
                status="OK",
                sql=llm_result.sql,
                can_execute_sql=True,
                reason="SQL was generated by controlled LLM fallback and must pass SQL Validator before execution.",
                prompt=built.prompt,
                modular_context=built.modular_context,
                warnings=llm_result.warnings,
                errors=llm_result.errors,
                metadata={"provider": llm_result.provider, "model": llm_result.model, "llm_status": llm_result.status},
            ).to_dict()
        return LLMSQLFallbackResult(
            status=llm_result.status,
            can_execute_sql=False,
            reason="LLM fallback did not return a SQL statement.",
            prompt=built.prompt,
            modular_context=built.modular_context,
            warnings=llm_result.warnings,
            errors=llm_result.errors,
            metadata={"provider": llm_result.provider, "model": llm_result.model},
        ).to_dict()

    def run(self, **kwargs: Any) -> JsonDict:
        return self.generate(**kwargs)

    async def arun(self, **kwargs: Any) -> JsonDict:
        return self.generate(**kwargs)

    def __call__(self, **kwargs: Any) -> JsonDict:
        return self.generate(**kwargs)


__all__ = ["LLMSQLFallback", "LLMSQLFallbackResult"]
